// data.js — Norwegian golf courses, weather, tee times, i18n
// All data is fictional but plausible; Norwegian club names are real or realistic.

window.TEE_DATA = (() => {

  // ─────────────────────────────────────────────────────────────
  // i18n
  // ─────────────────────────────────────────────────────────────
  const i18n = {
    no: {
      brand: 'tee.',
      tagline: 'Spill mer. Bestill mindre.',
      discover: 'Oppdag',
      tonight: 'I kveld',
      thisWeek: 'Denne uken',
      nearMe: 'Nær meg',
      todaysWindow: 'Dagens vindu',
      golden: 'Gyllent',
      calm: 'Stille',
      breezy: 'Frisk',
      windy: 'Vind',
      perfectWindow: 'Perfekt vindu',
      decentWindow: 'Greit vindu',
      conditions: 'Forhold',
      greens: 'Greener',
      fairway: 'Fairway',
      rough: 'Rough',
      stimp: 'Stimp',
      firm: 'Fast',
      soft: 'Mykt',
      medium: 'Middels',
      mowed: 'Klippet',
      hourAgo: 't siden',
      open: 'Åpen',
      twilight: 'Tussmørke',
      seeAvailability: 'Se ledige tider',
      pickATime: 'Velg en tid',
      window: 'Vinduet',
      readyForGolf: 'Klar for runden',
      yourGroup: 'Din gruppe',
      addPlayer: 'Legg til spiller',
      handicap: 'Hcp',
      payTogether: 'Betal samlet',
      payIndividually: 'Hver for seg',
      total: 'Totalt',
      confirm: 'Bekreft bestilling',
      booked: 'Booket',
      yourTeeTime: 'Din tid',
      driveTime: 'Kjøretid',
      shareWithGroup: 'Del med gruppen',
      checkIn: 'Sjekk inn',
      from: 'Fra',
      kr: 'kr',
      perPlayer: 'pr. spiller',
      sunrise: 'Soloppgang',
      sunset: 'Solnedgang',
      goldenHour: 'Gylden time',
      windKmh: 'm/s',
      now: 'Nå',
      hole: 'Hull',
      par: 'Par',
      yards: 'm',
      signature: 'Signaturhullet',
      morning: 'Morgen',
      midday: 'Midt på dagen',
      evening: 'Kveld',
      late: 'Sent',
      free: 'ledig',
      taken: 'tatt',
      players: 'spillere',
      player: 'spiller',
      anytime: 'Når som helst',
      mins: 'min',
      readyIn: 'Klar om',
      practice: 'Driving range',
      caddie: 'Caddie',
      cart: 'Tralle',
      walking: 'Til fots',
      memberRate: 'Medlemspris',
      guest: 'Gjest',
      back: 'Tilbake',
      next: 'Neste',
      payNow: 'Betal nå',
      vipps: 'Vipps',
      apple: 'Apple Pay',
      card: 'Kort',
      youreIn: 'Du er inne',
      shareCode: 'Del koden',
      addToWallet: 'Legg til i Wallet',
      cancelFree: 'Gratis avbestilling før 24t',
      teeBox: 'Tee-boks',
      par72: 'Par 72',
      holes18: '18 hull',
      forecast: 'Værmelding',
      rainExpected: 'Regn ventet',
      tempDrops: 'Temp faller',
      windPicksUp: 'Vinden tar seg opp',
      bestNow: 'Beste nå',
      addNotes: 'Legg til notat',
      groupMessage: 'Melding til gruppen',
      onTheTee: 'På tee',
      lookingFor: 'Hva ser du etter?',
    },
    en: {
      brand: 'tee.',
      tagline: 'Play more. Book less.',
      discover: 'Discover',
      tonight: 'Tonight',
      thisWeek: 'This week',
      nearMe: 'Near me',
      todaysWindow: "Today's window",
      golden: 'Golden',
      calm: 'Calm',
      breezy: 'Breezy',
      windy: 'Windy',
      perfectWindow: 'Perfect window',
      decentWindow: 'Decent window',
      conditions: 'Conditions',
      greens: 'Greens',
      fairway: 'Fairway',
      rough: 'Rough',
      stimp: 'Stimp',
      firm: 'Firm',
      soft: 'Soft',
      medium: 'Medium',
      mowed: 'Mowed',
      hourAgo: 'h ago',
      open: 'Open',
      twilight: 'Twilight',
      seeAvailability: 'See available times',
      pickATime: 'Pick a time',
      window: 'The Window',
      readyForGolf: 'Ready to play',
      yourGroup: 'Your group',
      addPlayer: 'Add player',
      handicap: 'Hcp',
      payTogether: 'Pay together',
      payIndividually: 'Split the bill',
      total: 'Total',
      confirm: 'Confirm booking',
      booked: 'Booked',
      yourTeeTime: 'Your tee time',
      driveTime: 'Drive',
      shareWithGroup: 'Share with group',
      checkIn: 'Check in',
      from: 'From',
      kr: 'kr',
      perPlayer: 'per player',
      sunrise: 'Sunrise',
      sunset: 'Sunset',
      goldenHour: 'Golden hour',
      windKmh: 'm/s',
      now: 'Now',
      hole: 'Hole',
      par: 'Par',
      yards: 'm',
      signature: 'Signature hole',
      morning: 'Morning',
      midday: 'Midday',
      evening: 'Evening',
      late: 'Late',
      free: 'open',
      taken: 'taken',
      players: 'players',
      player: 'player',
      anytime: 'Anytime',
      mins: 'min',
      readyIn: 'Ready in',
      practice: 'Driving range',
      caddie: 'Caddie',
      cart: 'Buggy',
      walking: 'Walking',
      memberRate: 'Member rate',
      guest: 'Guest',
      back: 'Back',
      next: 'Next',
      payNow: 'Pay now',
      vipps: 'Vipps',
      apple: 'Apple Pay',
      card: 'Card',
      youreIn: "You're in",
      shareCode: 'Share code',
      addToWallet: 'Add to Wallet',
      cancelFree: 'Free cancellation up to 24h',
      teeBox: 'Tee box',
      par72: 'Par 72',
      holes18: '18 holes',
      forecast: 'Forecast',
      rainExpected: 'Rain expected',
      tempDrops: 'Temp drops',
      windPicksUp: 'Wind picks up',
      bestNow: 'Best now',
      addNotes: 'Add a note',
      groupMessage: 'Group message',
      onTheTee: 'On the tee',
      lookingFor: 'What are you after?',
    }
  };

  // ─────────────────────────────────────────────────────────────
  // Norwegian courses (real club names; data is illustrative)
  // ─────────────────────────────────────────────────────────────
  const courses = [
    {
      id: 'losby',
      name: 'Losby Golfklubb',
      location: 'Lørenskog',
      region: 'Oslo',
      holes: 18, par: 72, length: 6087,
      rating: 4.6, reviews: 318,
      blurb: { en: 'Old manor parkland, narrow doglegs through pine.', no: 'Gammel herregårdsbane, smale doglegs gjennom furuskog.' },
      signature: { en: 'Hole 14 — par 3 over the manor pond, green tucked behind oaks.', no: 'Hull 14 — par 3 over herregårdsdammen, green gjemt bak eik.' },
      drive: 22, // km from user
      driveMin: 28,
      pricePeak: 1100, priceOff: 750,
      hero: 'parkland', // visual key
      conditions: { greenSpeed: 9.8, fairway: 'firm', rough: 'medium', mowedHrsAgo: 2, cart: true, walking: true },
      sunrise: '04:38', sunset: '21:08', goldenStart: '19:45',
      // hourly weather index 5..21
      hourly: [
        { h:5, t:11, w:3, dir:'SW', sun:0.10, cloud:0.6 },
        { h:6, t:13, w:3, dir:'SW', sun:0.20, cloud:0.5 },
        { h:7, t:15, w:4, dir:'SW', sun:0.35, cloud:0.4 },
        { h:8, t:17, w:5, dir:'W',  sun:0.55, cloud:0.3 },
        { h:9, t:19, w:6, dir:'W',  sun:0.70, cloud:0.3 },
        { h:10,t:20, w:6, dir:'W',  sun:0.82, cloud:0.2 },
        { h:11,t:21, w:7, dir:'W',  sun:0.92, cloud:0.2 },
        { h:12,t:22, w:7, dir:'W',  sun:0.98, cloud:0.1 },
        { h:13,t:22, w:8, dir:'NW', sun:1.00, cloud:0.1 },
        { h:14,t:22, w:8, dir:'NW', sun:0.96, cloud:0.2 },
        { h:15,t:21, w:7, dir:'NW', sun:0.88, cloud:0.3 },
        { h:16,t:20, w:6, dir:'N',  sun:0.78, cloud:0.4 },
        { h:17,t:19, w:5, dir:'N',  sun:0.65, cloud:0.4 },
        { h:18,t:18, w:4, dir:'N',  sun:0.50, cloud:0.3 },
        { h:19,t:17, w:3, dir:'N',  sun:0.34, cloud:0.2 },
        { h:20,t:15, w:2, dir:'N',  sun:0.20, cloud:0.2 },
        { h:21,t:13, w:2, dir:'N',  sun:0.05, cloud:0.3 },
      ],
      // tee time slots (8min increments). availSlots: 1-4 spots remaining.
      teeTimes: genTeeTimes('losby'),
      window: { start:18, end:20, label:'golden' },
    },
    {
      id: 'larvik',
      name: 'Larvik Golfklubb',
      location: 'Larvik',
      region: 'Vestfold',
      holes: 18, par: 71, length: 5742,
      rating: 4.8, reviews: 412,
      blurb: { en: 'Coastal links along the Skagerrak — wind plays here.', no: 'Kystlinks langs Skagerrak — vinden er en spiller.' },
      signature: { en: 'Hole 7 — drive blind over a granite ridge to a fairway hugging the sea.', no: 'Hull 7 — blindt drive over granittrygg til fairway tett ved sjøen.' },
      drive: 132, driveMin: 100,
      pricePeak: 950, priceOff: 650,
      hero: 'links',
      conditions: { greenSpeed: 10.4, fairway: 'firm', rough: 'long', mowedHrsAgo: 5, cart: false, walking: true },
      sunrise: '04:48', sunset: '21:35', goldenStart: '20:10',
      hourly: [
        { h:5, t:12, w:6, dir:'SW', sun:0.10, cloud:0.4 },
        { h:6, t:13, w:7, dir:'SW', sun:0.22, cloud:0.3 },
        { h:7, t:14, w:8, dir:'SW', sun:0.38, cloud:0.3 },
        { h:8, t:16, w:9, dir:'W',  sun:0.55, cloud:0.2 },
        { h:9, t:18, w:10,dir:'W',  sun:0.72, cloud:0.2 },
        { h:10,t:19, w:11,dir:'W',  sun:0.85, cloud:0.2 },
        { h:11,t:20, w:12,dir:'W',  sun:0.94, cloud:0.1 },
        { h:12,t:21, w:13,dir:'W',  sun:1.00, cloud:0.1 },
        { h:13,t:21, w:13,dir:'NW', sun:0.97, cloud:0.1 },
        { h:14,t:20, w:12,dir:'NW', sun:0.90, cloud:0.2 },
        { h:15,t:20, w:11,dir:'NW', sun:0.82, cloud:0.2 },
        { h:16,t:19, w:9, dir:'N',  sun:0.72, cloud:0.2 },
        { h:17,t:18, w:7, dir:'N',  sun:0.60, cloud:0.2 },
        { h:18,t:17, w:5, dir:'N',  sun:0.46, cloud:0.2 },
        { h:19,t:16, w:4, dir:'N',  sun:0.32, cloud:0.2 },
        { h:20,t:15, w:3, dir:'N',  sun:0.18, cloud:0.3 },
        { h:21,t:14, w:3, dir:'N',  sun:0.04, cloud:0.4 },
      ],
      teeTimes: genTeeTimes('larvik'),
      window: { start:17, end:19, label:'calm-after-wind' },
    },
    {
      id: 'miklagard',
      name: 'Miklagard Golf',
      location: 'Kløfta',
      region: 'Oslo',
      holes: 18, par: 73, length: 6321,
      rating: 4.7, reviews: 528,
      blurb: { en: 'Championship layout, big greens, generous fairways framed by birch.', no: 'Mesterskapsbane, store greener, generøse fairways i bjørkeskog.' },
      signature: { en: 'Hole 18 — island green approach, wind off the lake.', no: 'Hull 18 — øy-green med vind fra vannet.' },
      drive: 38, driveMin: 36,
      pricePeak: 1350, priceOff: 950,
      hero: 'championship',
      conditions: { greenSpeed: 11.2, fairway: 'firm', rough: 'medium', mowedHrsAgo: 1, cart: true, walking: true },
      sunrise: '04:35', sunset: '21:12', goldenStart: '19:50',
      hourly: [
        { h:5, t:10, w:2, dir:'SE', sun:0.10, cloud:0.3 },
        { h:6, t:12, w:2, dir:'SE', sun:0.22, cloud:0.2 },
        { h:7, t:14, w:3, dir:'SE', sun:0.38, cloud:0.2 },
        { h:8, t:16, w:3, dir:'S',  sun:0.55, cloud:0.1 },
        { h:9, t:18, w:4, dir:'S',  sun:0.72, cloud:0.1 },
        { h:10,t:20, w:5, dir:'S',  sun:0.85, cloud:0.1 },
        { h:11,t:21, w:5, dir:'S',  sun:0.94, cloud:0.1 },
        { h:12,t:22, w:6, dir:'SW', sun:1.00, cloud:0.1 },
        { h:13,t:23, w:6, dir:'SW', sun:0.97, cloud:0.1 },
        { h:14,t:23, w:7, dir:'SW', sun:0.90, cloud:0.2 },
        { h:15,t:22, w:6, dir:'SW', sun:0.82, cloud:0.2 },
        { h:16,t:21, w:6, dir:'W',  sun:0.72, cloud:0.2 },
        { h:17,t:20, w:5, dir:'W',  sun:0.60, cloud:0.2 },
        { h:18,t:19, w:4, dir:'W',  sun:0.46, cloud:0.2 },
        { h:19,t:18, w:3, dir:'NW', sun:0.32, cloud:0.2 },
        { h:20,t:16, w:2, dir:'NW', sun:0.18, cloud:0.2 },
        { h:21,t:14, w:2, dir:'N',  sun:0.04, cloud:0.2 },
      ],
      teeTimes: genTeeTimes('miklagard'),
      window: { start:8, end:11, label:'morning-calm' },
    },
    {
      id: 'tyrifjord',
      name: 'Tyrifjord Golfklubb',
      location: 'Vikersund',
      region: 'Buskerud',
      holes: 18, par: 71, length: 5810,
      rating: 4.5, reviews: 187,
      blurb: { en: 'Lakeside fairways with the Tyrifjord shimmering through the pines.', no: 'Fairways langs Tyrifjorden, gjennom furutoppene.' },
      signature: { en: 'Hole 12 — par 5 hugging the lake the whole way home.', no: 'Hull 12 — par 5 langs vannet hele veien hjem.' },
      drive: 71, driveMin: 58,
      pricePeak: 750, priceOff: 500,
      hero: 'lakeside',
      conditions: { greenSpeed: 9.0, fairway: 'medium', rough: 'medium', mowedHrsAgo: 6, cart: true, walking: true },
      sunrise: '04:42', sunset: '21:18', goldenStart: '19:55',
      hourly: [],
      teeTimes: [],
      window: { start:14, end:17, label:'midday' },
    },
    {
      id: 'atlungstad',
      name: 'Atlungstad Golfklubb',
      location: 'Stange',
      region: 'Innlandet',
      holes: 18, par: 72, length: 5950,
      rating: 4.4, reviews: 156,
      blurb: { en: 'Rolling farmland next to Lake Mjøsa.', no: 'Bølgende jordbrukslandskap ved Mjøsa.' },
      signature: { en: 'Hole 9 — long par 4 down to the lake.', no: 'Hull 9 — lang par 4 ned mot Mjøsa.' },
      drive: 110, driveMin: 78,
      pricePeak: 700, priceOff: 480,
      hero: 'farmland',
      conditions: { greenSpeed: 9.2, fairway: 'firm', rough: 'short', mowedHrsAgo: 3, cart: true, walking: true },
      sunrise: '04:22', sunset: '21:48', goldenStart: '20:25',
      hourly: [],
      teeTimes: [],
      window: { start:6, end:9, label:'morning' },
    },
  ];

  function genTeeTimes(seed) {
    // generate 8-min slots from 06:00 to 20:00
    const out = [];
    let n = seed.length * 17; // pseudo seed
    const rand = () => { n = (n * 9301 + 49297) % 233280; return n / 233280; };
    for (let h = 6; h < 20; h++) {
      for (let m = 0; m < 60; m += 8) {
        const r = rand();
        const r2 = rand();
        const avail = r < 0.18 ? 0 : r < 0.45 ? Math.ceil(r2 * 4) : 4;
        // Peak pricing 09–18 weekdays
        const peak = h >= 9 && h <= 17;
        // golden window slight premium 18–20
        const golden = h >= 18;
        const price = peak ? 1100 : golden ? 950 : 750;
        out.push({
          time: `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`,
          h, m,
          avail,
          taken: 4 - avail,
          price,
          peak, golden,
        });
      }
    }
    return out;
  }

  // ─────────────────────────────────────────────────────────────
  // Sample group
  // ─────────────────────────────────────────────────────────────
  const players = [
    { id: 'me', name: 'Mathias', initials: 'M', hcp: 14.2, you: true },
    { id: 'kjetil', name: 'Kjetil', initials: 'K', hcp: 8.4 },
    { id: 'silje', name: 'Silje', initials: 'S', hcp: 22.1 },
    { id: 'erik', name: 'Erik', initials: 'E', hcp: 17.8 },
  ];

  const friends = [
    { id: 'kjetil', name: 'Kjetil Sørli', hcp: 8.4 },
    { id: 'silje',  name: 'Silje Berg',   hcp: 22.1 },
    { id: 'erik',   name: 'Erik Holm',    hcp: 17.8 },
    { id: 'jonas',  name: 'Jonas Lie',    hcp: 11.0 },
    { id: 'astri',  name: 'Astri Vik',    hcp: 19.3 },
  ];

  return { i18n, courses, players, friends };
})();
