"""Seed legal source metadata for StrikeLab's open golf data layer."""
from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy.orm import Session

from app.models import DataSource


DATA_SOURCES: list[dict[str, Any]] = [
    {
        "id": "ngf-public-directory",
        "name": "Norges Golfforbund public club directory",
        "category": "courses",
        "license_name": "Public directory data; verify reuse before redistribution",
        "license_url": "https://www.golfforbundet.no/",
        "attribution": "Club metadata derived from public NGF/GolfBox club listings and club websites.",
        "source_url": "https://www.golfforbundet.no/",
        "terms_url": "https://www.golfforbundet.no/",
        "refresh_interval_hours": 24 * 30,
        "is_open": False,
        "notes": "Used for Norway-first seed catalog. Keep factual fields only and verify any expanded redistribution terms before exposing bulk export.",
    },
    {
        "id": "openstreetmap",
        "name": "OpenStreetMap",
        "category": "courses",
        "license_name": "Open Database License 1.0",
        "license_url": "https://www.openstreetmap.org/copyright",
        "attribution": "© OpenStreetMap contributors",
        "source_url": "https://www.openstreetmap.org/",
        "terms_url": "https://osmfoundation.org/wiki/Licence",
        "refresh_interval_hours": 24 * 7,
        "is_open": True,
        "notes": "Used through Overpass for course coordinates and hole-level golf features. ODbL attribution and share-alike obligations apply to derived database extracts.",
    },
    {
        "id": "met-no",
        "name": "MET Norway Locationforecast",
        "category": "weather",
        "license_name": "Norwegian Licence for Open Government Data (NLOD) / CC BY 4.0 compatible service terms",
        "license_url": "https://api.met.no/license_data.html",
        "attribution": "Weather data from MET Norway",
        "source_url": "https://api.met.no/weatherapi/locationforecast/2.0/documentation",
        "terms_url": "https://api.met.no/conditions_service.html",
        "refresh_interval_hours": 1,
        "is_open": True,
        "notes": "Preferred Norway weather source. Requires identifying User-Agent and attribution.",
    },
    {
        "id": "open-meteo",
        "name": "Open-Meteo",
        "category": "weather",
        "license_name": "CC BY 4.0 data; API terms vary by usage",
        "license_url": "https://open-meteo.com/en/license",
        "attribution": "Weather data by Open-Meteo.com",
        "source_url": "https://open-meteo.com/",
        "terms_url": "https://open-meteo.com/en/terms",
        "refresh_interval_hours": 1,
        "is_open": True,
        "notes": "Fallback weather source outside MET Norway coverage and for additional forecast variables.",
    },
    {
        "id": "sunrise-sunset",
        "name": "Sunrise-Sunset.org",
        "category": "daylight",
        "license_name": "Free API terms",
        "license_url": "https://sunrise-sunset.org/terms",
        "attribution": "Sunrise and sunset data from Sunrise-Sunset.org",
        "source_url": "https://sunrise-sunset.org/api",
        "terms_url": "https://sunrise-sunset.org/terms",
        "refresh_interval_hours": 24,
        "is_open": True,
        "notes": "Used for daylight and golden-window calculations when upstream forecast payloads do not include daylight.",
    },
    {
        "id": "strikelab-synthesized-conditions",
        "name": "StrikeLab synthesized conditions",
        "category": "weather",
        "license_name": "StrikeLab generated fallback",
        "license_url": "https://strikelab.golf/terms",
        "attribution": "Fallback playing conditions generated by StrikeLab when upstream weather or daylight services are unavailable.",
        "source_url": "https://strikelab.golf",
        "terms_url": "https://strikelab.golf/terms",
        "refresh_interval_hours": 1,
        "is_open": False,
        "notes": "Deterministic degraded-mode forecast for UI continuity. Do not present as observed weather.",
    },
    {
        "id": "strikelab-equipment",
        "name": "StrikeLab equipment catalog",
        "category": "equipment",
        "license_name": "StrikeLab maintained factual catalog",
        "license_url": "https://strikelab.golf/terms",
        "attribution": "Equipment metadata maintained by StrikeLab from manufacturer-published specifications and user corrections.",
        "source_url": "https://strikelab.golf",
        "terms_url": "https://strikelab.golf/terms",
        "refresh_interval_hours": 24 * 30,
        "is_open": False,
        "notes": "Brand/model facts only. Avoid copying proprietary marketing text or imagery without permission.",
    },
    {
        "id": "golfcourseapi",
        "name": "Golf Course API",
        "category": "courses",
        "license_name": "Commercial API terms",
        "license_url": "https://www.golfcourseapi.com/",
        "attribution": "Course rating and tee data from Golf Course API where available.",
        "source_url": "https://api.golfcourseapi.com/docs/api/",
        "terms_url": "https://www.golfcourseapi.com/",
        "refresh_interval_hours": 24 * 30,
        "is_open": False,
        "notes": "Provider currently verifies for US courses; Norway coverage must be treated as limited until queries return Norwegian clubs.",
    },
]


def seed_data_sources(db: Session) -> int:
    count = 0
    now = datetime.utcnow()
    for row in DATA_SOURCES:
        existing = db.get(DataSource, row["id"])
        payload = {**row, "updated_at": now}
        if existing:
            for key, value in payload.items():
                setattr(existing, key, value)
        else:
            db.add(DataSource(**payload))
        count += 1
    db.commit()
    return count
