// Golf Courses Database
export interface GolfCourse {
  id: string
  name: string
  city: string
  region?: string
  country: string
  countryCode: string
  par: number
  holes: number
  courseRating?: number
  slopeRating?: number
  length?: number // in meters
  lengthYards?: number
  established?: number
  designer?: string
  type: 'links' | 'parkland' | 'heathland' | 'desert' | 'mountain' | 'resort'
  facilities: string[]
  website?: string
  phone?: string
  latitude?: number
  longitude?: number
  priceRange: 'budget' | 'moderate' | 'premium' | 'luxury'
  imageUrl?: string
  description?: string
  holeData?: HoleData[]
}

export interface HoleData {
  number: number
  par: number
  handicap: number
  whiteTee?: number // meters
  yellowTee?: number
  blueTee?: number
  redTee?: number
}

// Norwegian Golf Courses
export const NORWEGIAN_COURSES: GolfCourse[] = [
  {
    id: 'oslo-gc',
    name: 'Oslo Golf Club',
    city: 'Oslo',
    region: 'Oslo',
    country: 'Norway',
    countryCode: 'NO',
    par: 72,
    holes: 18,
    courseRating: 73.4,
    slopeRating: 136,
    length: 6215,
    established: 1924,
    designer: 'Tom Simpson',
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'driving_range', 'putting_green', 'locker_room'],
    website: 'https://www.oslogk.no',
    phone: '+47 22 51 05 60',
    latitude: 59.9583,
    longitude: 10.8015,
    priceRange: 'premium',
    description: 'One of Norway\'s oldest and most prestigious golf clubs, featuring a classic parkland layout designed by renowned architect Tom Simpson.',
  },
  {
    id: 'bogstad-gk',
    name: 'Bogstad Golf Club',
    city: 'Oslo',
    region: 'Oslo',
    country: 'Norway',
    countryCode: 'NO',
    par: 72,
    holes: 18,
    courseRating: 71.8,
    slopeRating: 128,
    length: 5890,
    established: 1972,
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'driving_range', 'putting_green', 'academy'],
    website: 'https://www.bogstadgolfklubb.no',
    latitude: 59.9721,
    longitude: 10.6458,
    priceRange: 'moderate',
    description: 'Popular Oslo-area course set in beautiful parkland near Bogstad Manor.',
  },
  {
    id: 'losby-gk',
    name: 'Losby Golf Club',
    city: 'Lørenskog',
    region: 'Akershus',
    country: 'Norway',
    countryCode: 'NO',
    par: 72,
    holes: 18,
    courseRating: 73.1,
    slopeRating: 134,
    length: 6158,
    established: 1989,
    designer: 'Robert Trent Jones Jr.',
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'hotel', 'spa', 'driving_range', 'putting_green'],
    website: 'https://www.losby.no',
    latitude: 59.9342,
    longitude: 11.0856,
    priceRange: 'luxury',
    description: 'Championship course designed by Robert Trent Jones Jr., featuring a luxury hotel and spa.',
  },
  {
    id: 'miklagard-gc',
    name: 'Miklagard Golf Club',
    city: 'Kløfta',
    region: 'Akershus',
    country: 'Norway',
    countryCode: 'NO',
    par: 72,
    holes: 18,
    courseRating: 73.8,
    slopeRating: 138,
    length: 6405,
    established: 1993,
    designer: 'Robert Trent Jones Jr.',
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'driving_range', 'short_game_area', 'putting_green'],
    website: 'https://www.miklagard.no',
    latitude: 60.0667,
    longitude: 11.1167,
    priceRange: 'premium',
    description: 'One of Norway\'s top courses, often ranked among the best in Scandinavia.',
  },
  {
    id: 'stavanger-gc',
    name: 'Stavanger Golf Club',
    city: 'Stavanger',
    region: 'Rogaland',
    country: 'Norway',
    countryCode: 'NO',
    par: 72,
    holes: 18,
    courseRating: 72.5,
    slopeRating: 132,
    length: 6050,
    established: 1956,
    type: 'links',
    facilities: ['pro_shop', 'restaurant', 'driving_range', 'putting_green'],
    website: 'https://www.stavangergk.no',
    latitude: 58.9525,
    longitude: 5.6827,
    priceRange: 'moderate',
    description: 'Links-style course on Norway\'s stunning west coast.',
  },
  {
    id: 'bergen-gc',
    name: 'Bergen Golf Club',
    city: 'Bergen',
    region: 'Vestland',
    country: 'Norway',
    countryCode: 'NO',
    par: 70,
    holes: 18,
    courseRating: 70.2,
    slopeRating: 126,
    length: 5650,
    established: 1958,
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'driving_range'],
    website: 'https://www.bergengk.no',
    latitude: 60.3195,
    longitude: 5.3642,
    priceRange: 'moderate',
    description: 'Scenic course with mountain views in Norway\'s second-largest city.',
  },
  {
    id: 'trondheim-gc',
    name: 'Trondheim Golf Club',
    city: 'Trondheim',
    region: 'Trøndelag',
    country: 'Norway',
    countryCode: 'NO',
    par: 72,
    holes: 18,
    courseRating: 71.9,
    slopeRating: 130,
    length: 5920,
    established: 1948,
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'driving_range', 'academy'],
    website: 'https://www.trondheimgk.no',
    latitude: 63.4165,
    longitude: 10.4248,
    priceRange: 'moderate',
    description: 'Historic course in the heart of central Norway.',
  },
  {
    id: 'bjaavann-gc',
    name: 'Bjaavann Golf Club',
    city: 'Kristiansand',
    region: 'Agder',
    country: 'Norway',
    countryCode: 'NO',
    par: 72,
    holes: 18,
    courseRating: 73.2,
    slopeRating: 135,
    length: 6180,
    established: 1992,
    designer: 'Jeremy Turner',
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'driving_range', 'short_game_area'],
    website: 'https://www.bjaavann.no',
    latitude: 58.1467,
    longitude: 8.0589,
    priceRange: 'premium',
    description: 'Southern Norway\'s premier championship course.',
  },
  {
    id: 'holtsmark-gc',
    name: 'Holtsmark Golf Club',
    city: 'Drammen',
    region: 'Buskerud',
    country: 'Norway',
    countryCode: 'NO',
    par: 72,
    holes: 18,
    courseRating: 71.5,
    slopeRating: 127,
    length: 5800,
    established: 1967,
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'driving_range'],
    website: 'https://www.holtsmark.no',
    latitude: 59.7439,
    longitude: 10.2045,
    priceRange: 'moderate',
    description: 'Challenging parkland course west of Oslo.',
  },
  {
    id: 'hafjell-gc',
    name: 'Hafjell Golf Club',
    city: 'Øyer',
    region: 'Innlandet',
    country: 'Norway',
    countryCode: 'NO',
    par: 72,
    holes: 18,
    courseRating: 72.8,
    slopeRating: 133,
    length: 6100,
    established: 1995,
    type: 'mountain',
    facilities: ['pro_shop', 'restaurant', 'hotel', 'driving_range'],
    website: 'https://www.hafjellgolf.no',
    latitude: 61.2333,
    longitude: 10.4833,
    priceRange: 'premium',
    description: 'Mountain course with stunning views of the Gudbrandsdalen valley.',
  },
  {
    id: 'kongsvinger-gc',
    name: 'Kongsvinger Golf Club',
    city: 'Kongsvinger',
    region: 'Innlandet',
    country: 'Norway',
    countryCode: 'NO',
    par: 72,
    holes: 18,
    courseRating: 71.2,
    slopeRating: 125,
    length: 5750,
    established: 1989,
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'driving_range'],
    priceRange: 'budget',
    description: 'Friendly parkland course near the Swedish border.',
  },
  {
    id: 'norum-gc',
    name: 'Norum Golf Club',
    city: 'Fredrikstad',
    region: 'Østfold',
    country: 'Norway',
    countryCode: 'NO',
    par: 72,
    holes: 18,
    courseRating: 72.4,
    slopeRating: 131,
    length: 6050,
    established: 1991,
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'driving_range', 'academy'],
    website: 'https://www.norumgolf.no',
    priceRange: 'moderate',
    description: 'Well-maintained course in southeastern Norway.',
  },
]

// International Famous Courses
export const INTERNATIONAL_COURSES: GolfCourse[] = [
  {
    id: 'st-andrews-old',
    name: 'The Old Course at St Andrews',
    city: 'St Andrews',
    region: 'Fife',
    country: 'Scotland',
    countryCode: 'GB',
    par: 72,
    holes: 18,
    courseRating: 73.1,
    slopeRating: 132,
    length: 6721,
    established: 1400,
    type: 'links',
    facilities: ['pro_shop', 'restaurant', 'caddie_service', 'museum'],
    website: 'https://www.standrews.com',
    latitude: 56.3433,
    longitude: -2.8024,
    priceRange: 'luxury',
    description: 'The Home of Golf - the oldest and most iconic golf course in the world.',
  },
  {
    id: 'augusta-national',
    name: 'Augusta National Golf Club',
    city: 'Augusta',
    region: 'Georgia',
    country: 'USA',
    countryCode: 'US',
    par: 72,
    holes: 18,
    courseRating: 76.2,
    slopeRating: 148,
    length: 7475,
    established: 1933,
    designer: 'Alister MacKenzie & Bobby Jones',
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'caddie_service'],
    priceRange: 'luxury',
    description: 'Home of the Masters Tournament - one of the most exclusive and beautiful courses in the world.',
  },
  {
    id: 'pebble-beach',
    name: 'Pebble Beach Golf Links',
    city: 'Pebble Beach',
    region: 'California',
    country: 'USA',
    countryCode: 'US',
    par: 72,
    holes: 18,
    courseRating: 75.5,
    slopeRating: 145,
    length: 6828,
    established: 1919,
    designer: 'Jack Neville & Douglas Grant',
    type: 'links',
    facilities: ['pro_shop', 'restaurant', 'hotel', 'spa', 'caddie_service'],
    website: 'https://www.pebblebeach.com',
    latitude: 36.5671,
    longitude: -121.9503,
    priceRange: 'luxury',
    description: 'Stunning coastal course along the Pacific Ocean, host to multiple U.S. Opens.',
  },
  {
    id: 'royal-county-down',
    name: 'Royal County Down',
    city: 'Newcastle',
    region: 'County Down',
    country: 'Northern Ireland',
    countryCode: 'GB',
    par: 71,
    holes: 18,
    courseRating: 74.5,
    slopeRating: 143,
    length: 7186,
    established: 1889,
    designer: 'Old Tom Morris',
    type: 'links',
    facilities: ['pro_shop', 'restaurant', 'caddie_service'],
    website: 'https://www.royalcountydown.org',
    priceRange: 'luxury',
    description: 'Regularly voted the best course in the world, with the Mountains of Mourne as a backdrop.',
  },
  {
    id: 'carnoustie',
    name: 'Carnoustie Golf Links - Championship',
    city: 'Carnoustie',
    region: 'Angus',
    country: 'Scotland',
    countryCode: 'GB',
    par: 72,
    holes: 18,
    courseRating: 75.2,
    slopeRating: 144,
    length: 7402,
    established: 1842,
    designer: 'Allan Robertson',
    type: 'links',
    facilities: ['pro_shop', 'restaurant', 'golf_academy'],
    website: 'https://www.carnoustiegolflinks.com',
    priceRange: 'premium',
    description: 'One of the toughest links courses in the Open Championship rotation.',
  },
  {
    id: 'royal-portrush',
    name: 'Royal Portrush - Dunluce',
    city: 'Portrush',
    region: 'County Antrim',
    country: 'Northern Ireland',
    countryCode: 'GB',
    par: 72,
    holes: 18,
    courseRating: 74.8,
    slopeRating: 141,
    length: 7344,
    established: 1888,
    designer: 'Harry Colt',
    type: 'links',
    facilities: ['pro_shop', 'restaurant', 'caddie_service'],
    website: 'https://www.royalportrushgolfclub.com',
    priceRange: 'premium',
    description: 'Host of The Open Championship, featuring dramatic clifftop holes.',
  },
  {
    id: 'turnberry-ailsa',
    name: 'Trump Turnberry - Ailsa',
    city: 'Turnberry',
    region: 'Ayrshire',
    country: 'Scotland',
    countryCode: 'GB',
    par: 72,
    holes: 18,
    courseRating: 74.3,
    slopeRating: 139,
    length: 7200,
    established: 1901,
    type: 'links',
    facilities: ['pro_shop', 'restaurant', 'hotel', 'spa', 'caddie_service'],
    website: 'https://www.turnberry.co.uk',
    priceRange: 'luxury',
    description: 'Iconic Scottish links with views of Ailsa Craig and the Isle of Arran.',
  },
  {
    id: 'muirfield',
    name: 'Muirfield - The Honourable Company',
    city: 'Gullane',
    region: 'East Lothian',
    country: 'Scotland',
    countryCode: 'GB',
    par: 71,
    holes: 18,
    courseRating: 74.1,
    slopeRating: 137,
    length: 7245,
    established: 1891,
    designer: 'Old Tom Morris',
    type: 'links',
    facilities: ['pro_shop', 'restaurant', 'caddie_service'],
    website: 'https://www.muirfield.org.uk',
    priceRange: 'luxury',
    description: 'Home of the oldest golf club in the world, featuring unique clockwise-counterclockwise routing.',
  },
  {
    id: 'bethpage-black',
    name: 'Bethpage Black',
    city: 'Farmingdale',
    region: 'New York',
    country: 'USA',
    countryCode: 'US',
    par: 71,
    holes: 18,
    courseRating: 77.5,
    slopeRating: 155,
    length: 7468,
    established: 1936,
    designer: 'A.W. Tillinghast',
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'driving_range'],
    priceRange: 'moderate',
    description: 'Public course famous for its "Warning" sign - one of the toughest in America.',
  },
  {
    id: 'ballybunion-old',
    name: 'Ballybunion Old Course',
    city: 'Ballybunion',
    region: 'County Kerry',
    country: 'Ireland',
    countryCode: 'IE',
    par: 71,
    holes: 18,
    courseRating: 73.8,
    slopeRating: 140,
    length: 6802,
    established: 1893,
    type: 'links',
    facilities: ['pro_shop', 'restaurant', 'caddie_service'],
    website: 'https://www.ballybuniongolfclub.ie',
    priceRange: 'premium',
    description: 'Wild Atlantic Way links, rated one of the finest natural courses anywhere.',
  },
  {
    id: 'valderrama',
    name: 'Real Club Valderrama',
    city: 'Sotogrande',
    region: 'Andalusia',
    country: 'Spain',
    countryCode: 'ES',
    par: 71,
    holes: 18,
    courseRating: 74.0,
    slopeRating: 142,
    length: 6356,
    established: 1974,
    designer: 'Robert Trent Jones Sr.',
    type: 'parkland',
    facilities: ['pro_shop', 'restaurant', 'caddie_service', 'driving_range'],
    website: 'https://www.valderrama.com',
    priceRange: 'luxury',
    description: 'Host of the 1997 Ryder Cup, the finest course in continental Europe.',
  },
  {
    id: 'barseback',
    name: 'Barsebäck Golf & Country Club - Masters',
    city: 'Landskrona',
    region: 'Skåne',
    country: 'Sweden',
    countryCode: 'SE',
    par: 72,
    holes: 18,
    courseRating: 73.5,
    slopeRating: 136,
    length: 6385,
    established: 1969,
    designer: 'Ture Bruce',
    type: 'links',
    facilities: ['pro_shop', 'restaurant', 'hotel', 'driving_range', 'academy'],
    website: 'https://www.bfrm.se',
    priceRange: 'premium',
    description: 'Sweden\'s best-known course, former host of the Solheim Cup.',
  },
  {
    id: 'wentworth-west',
    name: 'Wentworth - West Course',
    city: 'Virginia Water',
    region: 'Surrey',
    country: 'England',
    countryCode: 'GB',
    par: 72,
    holes: 18,
    courseRating: 74.2,
    slopeRating: 140,
    length: 7302,
    established: 1926,
    designer: 'Harry Colt',
    type: 'heathland',
    facilities: ['pro_shop', 'restaurant', 'spa', 'hotel', 'driving_range'],
    website: 'https://www.wentworthclub.com',
    priceRange: 'luxury',
    description: 'Home of the BMW PGA Championship, known as the Burma Road.',
  },
  {
    id: 'dubai-emirates',
    name: 'Emirates Golf Club - Majlis',
    city: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    par: 72,
    holes: 18,
    courseRating: 73.8,
    slopeRating: 133,
    length: 7301,
    established: 1988,
    designer: 'Karl Litten',
    type: 'desert',
    facilities: ['pro_shop', 'restaurant', 'hotel', 'spa', 'driving_range', 'floodlit_range'],
    website: 'https://www.dubaigolf.com',
    priceRange: 'luxury',
    description: 'The Middle East\'s first grass course, host of the Dubai Desert Classic.',
  },
  {
    id: 'kiawah-ocean',
    name: 'Kiawah Island - Ocean Course',
    city: 'Kiawah Island',
    region: 'South Carolina',
    country: 'USA',
    countryCode: 'US',
    par: 72,
    holes: 18,
    courseRating: 79.6,
    slopeRating: 155,
    length: 7876,
    established: 1991,
    designer: 'Pete Dye',
    type: 'links',
    facilities: ['pro_shop', 'restaurant', 'resort', 'caddie_service'],
    website: 'https://www.kiawahresort.com',
    priceRange: 'luxury',
    description: 'Site of the famous 1991 "War by the Shore" Ryder Cup.',
  },
]

// Combined courses list
export const ALL_COURSES: GolfCourse[] = [...NORWEGIAN_COURSES, ...INTERNATIONAL_COURSES]

// Helper functions
export function getCoursesByCountry(countryCode: string): GolfCourse[] {
  return ALL_COURSES.filter(c => c.countryCode === countryCode)
}

export function getCoursesByType(type: GolfCourse['type']): GolfCourse[] {
  return ALL_COURSES.filter(c => c.type === type)
}

export function getCoursesByPriceRange(range: GolfCourse['priceRange']): GolfCourse[] {
  return ALL_COURSES.filter(c => c.priceRange === range)
}

export function searchCourses(query: string): GolfCourse[] {
  const q = query.toLowerCase()
  return ALL_COURSES.filter(c => 
    c.name.toLowerCase().includes(q) ||
    c.city.toLowerCase().includes(q) ||
    c.country.toLowerCase().includes(q) ||
    (c.region?.toLowerCase().includes(q))
  )
}

export function getCourseById(id: string): GolfCourse | undefined {
  return ALL_COURSES.find(c => c.id === id)
}

// Country list for filtering
export const COURSE_COUNTRIES = [
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
]
